import:
  - ~/.config/alacritty/themes/thelovelace.yaml

key_bindings:
  - key: Paste
    action: Paste
  - key: V
    mods: Control
    action: Paste
  - key: F11
    action: ToggleFullscreen
  - key: F12
    action: SpawnNewInstance
font:
  size: 12
  normal:
    family: Hasklug Nerd Font
live_config_reload: true
window:
  decorations: none
selection:
  save_to_clipboard: true
cursor:
  blink_interval: 100
  style:
    shape: Underline
    blinking: 'On'
mouse:
  hide_when_typing: true
env:
  WINIT_HIDPI_FACTOR: '1'
