#! /usr/bin/env bash

nix-env -iA \
  nixpkgs.htop \
  nixpkgs.neovim \
  nixpkgs.unzip \
  nixpkgs.git \
  nixpkgs.tmux \
  nixpkgs.coreutils \
  nixpkgs.binutils \
  nixpkgs.findutils \
  nixpkgs.fzf \
  nixpkgs.python2 \
  nixpkgs.python3 \
  nixpkgs.python3Packages.pip \
  nixpkgs.python3Packages.setuptools \
  nixpkgs.tree \
  nixpkgs.htop \
  nixpkgs.weechat \
  nixpkgs.redis \
  nixpkgs.curl \
  nixpkgs.ctags \
  nixpkgs.shellcheck \
  nixpkgs.ripgrep-all \
  nixpkgs.nmap \
  nixpkgs.traceroute \
  nixpkgs.ping \
  nixpkgs.dig \
  nixpkgs.whois \
  nixpkgs.ag \
  nixpkgs.acpi \
  nixpkgs.bat \
  nixpkgs.tor \
  nixpkgs.openssh \
  nixpkgs.automake \
  nixpkgs.autoconf \
  nixpkgs.cmake \
  nixpkgs.nix-index \
  nixpkgs.python2Packages.setuptools \
  nixpkgs.gzip \
  nixpkgs.gnugrep \
  nixpkgs.ack \
  nixpkgs.acpi \
  nixpkgs.gawk \
  nixpkgs.gnused \
  nixpkgs.ps \
  nixpkgs.gnutar \
  nixpkgs.powertop \
  nixpkgs.telnet \
  nixpkgs.sudo \
  nixpkgs.su \
  nixpkgs.mcfly \
  nixpkgs.nginx \
  nixpkgs.postgresql \
  nixpkgs.bzip2 \
  nixpkgs.iw \
  nixpkgs.iwd \
  nixpkgs.rustc \
  nixpkgs.cargo \
  nixpkgs.killall \
  nixpkgs.which \
  nixpkgs.ping \
  nixpkgs.hostname \
  nixpkgs.nodejs-16_x \
  nixpkgs.phantomjs2 \
  nixpkgs.mpd \
  nixpkgs.ncmpcpp \
  nixpkgs.gnupg2 \
  nixpkgs.pass \
  nixpkgs.decompress \
  nixpkgs.nginx \
  nixpkgs.postgresql \
  nixpkgs.bzip2 \
  nixpkgs.gperf \
  nixpkgs.luajit \
  nixpkgs.luajitPackages.mpack \
  nixpkgs.luajitPackages.nvim-client \
  nixpkgs.luajitPackages.lpeg \
  nixpkgs.unibilium \
  nixpkgs.libmsgpack \
  nixpkgs.libtermkey \
  nixpkgs.shfmt
